name: bhavcopy cron job

on:
  schedule:
  - cron: 0/5 * * * *

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Create secret.json file
      run: echo "$SECRET_JSON" > secret.json
      env:
        SECRET_JSON: ${{ secrets.SECRET_JSON }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python your_script.py

    - name: Display generated file
      run: cat /tmp/test.txt
